// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSubmit(arg1) {
  return window['go']['main']['App']['CheckSubmit'](arg1);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function StopReading() {
  return window['go']['main']['App']['StopReading']();
}

export function UpdateGroups(arg1) {
  return window['go']['main']['App']['UpdateGroups'](arg1);
}
