// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckSubmit(arg1:string):Promise<void>;

export function GetGroups():Promise<Array<main.groupDefinition>>;

export function StopReading():Promise<void>;

export function UpdateGroups(arg1:string):Promise<void>;
